# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/researchadmin/ConvBlock/ConvBlock.srcs/sources_1/bd/Redesign/ip/Redesign_conv_engine_1_0/Redesign_conv_engine_1_0.xci
# IP: The module: 'Redesign_conv_engine_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_conv_engine_1_0/constraints/conv_engine_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Redesign_conv_engine_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/researchadmin/ConvBlock/ConvBlock.srcs/sources_1/bd/Redesign/ip/Redesign_conv_engine_1_0/Redesign_conv_engine_1_0.xci
# IP: The module: 'Redesign_conv_engine_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_conv_engine_1_0/constraints/conv_engine_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Redesign_conv_engine_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
