// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv_engine_conv_engine_Pipeline_FINALIZE_COL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_width,
        result_row_3_address0,
        result_row_3_ce0,
        result_row_3_we0,
        result_row_3_d0,
        result_row_2_address0,
        result_row_2_ce0,
        result_row_2_we0,
        result_row_2_d0,
        result_row_1_address0,
        result_row_1_ce0,
        result_row_1_we0,
        result_row_1_d0,
        result_row_address0,
        result_row_ce0,
        result_row_we0,
        result_row_d0,
        acc_buf_address0,
        acc_buf_ce0,
        acc_buf_q0,
        conv7_i,
        shl_i_i16_i_cast1372,
        tobool323,
        acc_buf_1_address0,
        acc_buf_1_ce0,
        acc_buf_1_q0,
        conv7_i_1,
        shl_i_i16_i_1_cast1378,
        acc_buf_2_address0,
        acc_buf_2_ce0,
        acc_buf_2_q0,
        conv7_i_2,
        shl_i_i16_i_2_cast1380,
        acc_buf_3_address0,
        acc_buf_3_ce0,
        acc_buf_3_q0,
        conv7_i_3,
        sext_ln148,
        oc_count,
        empty_54,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] out_width;
output  [8:0] result_row_3_address0;
output   result_row_3_ce0;
output   result_row_3_we0;
output  [15:0] result_row_3_d0;
output  [8:0] result_row_2_address0;
output   result_row_2_ce0;
output   result_row_2_we0;
output  [15:0] result_row_2_d0;
output  [8:0] result_row_1_address0;
output   result_row_1_ce0;
output   result_row_1_we0;
output  [15:0] result_row_1_d0;
output  [8:0] result_row_address0;
output   result_row_ce0;
output   result_row_we0;
output  [15:0] result_row_d0;
output  [8:0] acc_buf_address0;
output   acc_buf_ce0;
input  [31:0] acc_buf_q0;
input  [15:0] conv7_i;
input  [31:0] shl_i_i16_i_cast1372;
input  [0:0] tobool323;
output  [8:0] acc_buf_1_address0;
output   acc_buf_1_ce0;
input  [31:0] acc_buf_1_q0;
input  [15:0] conv7_i_1;
input  [31:0] shl_i_i16_i_1_cast1378;
output  [8:0] acc_buf_2_address0;
output   acc_buf_2_ce0;
input  [31:0] acc_buf_2_q0;
input  [15:0] conv7_i_2;
input  [31:0] shl_i_i16_i_2_cast1380;
output  [8:0] acc_buf_3_address0;
output   acc_buf_3_ce0;
input  [31:0] acc_buf_3_q0;
input  [15:0] conv7_i_3;
input  [31:0] sext_ln148;
input  [31:0] oc_count;
input  [30:0] empty_54;
input  [29:0] empty;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln288_fu_392_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [47:0] sext_ln148_cast_fu_324_p1;
reg  signed [47:0] sext_ln148_cast_reg_1388;
wire  signed [47:0] conv7_i_3_cast_fu_328_p1;
reg  signed [47:0] conv7_i_3_cast_reg_1393;
wire  signed [47:0] shl_i_i16_i_2_cast1380_cast_fu_332_p1;
reg  signed [47:0] shl_i_i16_i_2_cast1380_cast_reg_1398;
wire  signed [47:0] conv7_i_2_cast_fu_336_p1;
reg  signed [47:0] conv7_i_2_cast_reg_1403;
wire  signed [47:0] shl_i_i16_i_1_cast1378_cast_fu_340_p1;
reg  signed [47:0] shl_i_i16_i_1_cast1378_cast_reg_1408;
wire  signed [47:0] conv7_i_1_cast_fu_344_p1;
reg  signed [47:0] conv7_i_1_cast_reg_1413;
wire  signed [47:0] shl_i_i16_i_cast1372_cast_fu_348_p1;
reg  signed [47:0] shl_i_i16_i_cast1372_cast_reg_1418;
wire  signed [47:0] conv7_i_cast_fu_352_p1;
reg  signed [47:0] conv7_i_cast_reg_1423;
wire   [0:0] icmp_ln135_fu_356_p2;
reg   [0:0] icmp_ln135_reg_1428;
wire   [0:0] icmp199_fu_362_p2;
reg   [0:0] icmp199_reg_1432;
wire   [0:0] cmp216_24019200_fu_368_p2;
reg   [0:0] cmp216_24019200_reg_1436;
wire   [0:0] icmp100201_fu_374_p2;
reg   [0:0] icmp100201_reg_1440;
wire   [63:0] zext_ln288_fu_404_p1;
reg   [63:0] zext_ln288_reg_1448;
reg   [63:0] zext_ln288_reg_1448_pp0_iter1_reg;
wire   [0:0] tmp_14_fu_427_p3;
reg   [0:0] tmp_14_reg_1476;
wire   [15:0] bn_out_1_fu_465_p2;
reg   [15:0] bn_out_1_reg_1481;
wire   [0:0] and_ln296_fu_485_p2;
reg   [0:0] and_ln296_reg_1486;
wire   [0:0] icmp_ln296_1_fu_525_p2;
reg   [0:0] icmp_ln296_1_reg_1491;
wire   [0:0] and_ln296_3_fu_583_p2;
reg   [0:0] and_ln296_3_reg_1496;
wire   [0:0] and_ln296_4_fu_589_p2;
reg   [0:0] and_ln296_4_reg_1502;
wire   [0:0] tmp_22_fu_605_p3;
reg   [0:0] tmp_22_reg_1507;
wire   [15:0] bn_out_4_fu_643_p2;
reg   [15:0] bn_out_4_reg_1512;
wire   [0:0] and_ln296_6_fu_663_p2;
reg   [0:0] and_ln296_6_reg_1517;
wire   [0:0] icmp_ln296_4_fu_703_p2;
reg   [0:0] icmp_ln296_4_reg_1522;
wire   [0:0] and_ln296_9_fu_761_p2;
reg   [0:0] and_ln296_9_reg_1527;
wire   [0:0] and_ln296_10_fu_767_p2;
reg   [0:0] and_ln296_10_reg_1533;
wire   [0:0] tmp_30_fu_783_p3;
reg   [0:0] tmp_30_reg_1538;
wire   [15:0] bn_out_7_fu_821_p2;
reg   [15:0] bn_out_7_reg_1543;
wire   [0:0] and_ln296_12_fu_841_p2;
reg   [0:0] and_ln296_12_reg_1548;
wire   [0:0] icmp_ln296_7_fu_881_p2;
reg   [0:0] icmp_ln296_7_reg_1553;
wire   [0:0] and_ln296_15_fu_939_p2;
reg   [0:0] and_ln296_15_reg_1558;
wire   [0:0] and_ln296_16_fu_945_p2;
reg   [0:0] and_ln296_16_reg_1564;
wire   [0:0] tmp_36_fu_961_p3;
reg   [0:0] tmp_36_reg_1569;
wire   [15:0] bn_out_10_fu_999_p2;
reg   [15:0] bn_out_10_reg_1574;
wire   [0:0] and_ln296_18_fu_1019_p2;
reg   [0:0] and_ln296_18_reg_1579;
wire   [0:0] icmp_ln296_10_fu_1059_p2;
reg   [0:0] icmp_ln296_10_reg_1584;
wire   [0:0] and_ln296_21_fu_1117_p2;
reg   [0:0] and_ln296_21_reg_1589;
wire   [0:0] and_ln296_22_fu_1123_p2;
reg   [0:0] and_ln296_22_reg_1595;
wire    ap_block_pp0_stage0;
reg   [30:0] col_fu_122;
wire   [30:0] add_ln288_fu_398_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_col_5;
reg    acc_buf_ce0_local;
reg    acc_buf_1_ce0_local;
reg    acc_buf_2_ce0_local;
reg    acc_buf_3_ce0_local;
reg    result_row_we0_local;
wire   [15:0] relu_out_fu_1181_p3;
reg    result_row_ce0_local;
reg    result_row_1_we0_local;
wire   [15:0] relu_out_1_fu_1242_p3;
reg    result_row_1_ce0_local;
reg    result_row_2_we0_local;
wire   [15:0] relu_out_2_fu_1303_p3;
reg    result_row_2_ce0_local;
reg    result_row_3_we0_local;
wire   [15:0] relu_out_3_fu_1364_p3;
reg    result_row_3_ce0_local;
wire  signed [15:0] mul_ln296_fu_308_p1;
wire  signed [15:0] mul_ln296_1_fu_312_p1;
wire  signed [15:0] mul_ln296_2_fu_316_p1;
wire  signed [15:0] mul_ln296_3_fu_320_p1;
wire   [31:0] zext_ln288_1_fu_388_p1;
wire   [47:0] mul_ln296_fu_308_p2;
wire   [47:0] add_ln296_fu_422_p2;
wire   [0:0] tmp_15_fu_445_p3;
wire   [15:0] bn_out_fu_435_p4;
wire   [15:0] zext_ln296_fu_461_p1;
wire   [0:0] tmp_17_fu_471_p3;
wire   [0:0] tmp_16_fu_453_p3;
wire   [0:0] xor_ln296_fu_479_p2;
wire   [14:0] tmp_6_fu_499_p4;
wire   [15:0] tmp_7_fu_515_p4;
wire   [0:0] icmp_ln296_2_fu_531_p2;
wire   [0:0] tmp_18_fu_491_p3;
wire   [0:0] icmp_ln296_fu_509_p2;
wire   [0:0] xor_ln296_1_fu_545_p2;
wire   [0:0] and_ln296_1_fu_551_p2;
wire   [0:0] select_ln296_fu_537_p3;
wire   [0:0] xor_ln296_2_fu_565_p2;
wire   [0:0] or_ln296_fu_571_p2;
wire   [0:0] xor_ln296_3_fu_577_p2;
wire   [0:0] select_ln296_1_fu_557_p3;
wire   [47:0] mul_ln296_1_fu_312_p2;
wire   [47:0] add_ln296_2_fu_600_p2;
wire   [0:0] tmp_23_fu_623_p3;
wire   [15:0] bn_out_3_fu_613_p4;
wire   [15:0] zext_ln296_1_fu_639_p1;
wire   [0:0] tmp_25_fu_649_p3;
wire   [0:0] tmp_24_fu_631_p3;
wire   [0:0] xor_ln296_5_fu_657_p2;
wire   [14:0] tmp_s_fu_677_p4;
wire   [15:0] tmp_8_fu_693_p4;
wire   [0:0] icmp_ln296_5_fu_709_p2;
wire   [0:0] tmp_28_fu_669_p3;
wire   [0:0] icmp_ln296_3_fu_687_p2;
wire   [0:0] xor_ln296_6_fu_723_p2;
wire   [0:0] and_ln296_7_fu_729_p2;
wire   [0:0] select_ln296_4_fu_715_p3;
wire   [0:0] xor_ln296_7_fu_743_p2;
wire   [0:0] or_ln296_2_fu_749_p2;
wire   [0:0] xor_ln296_8_fu_755_p2;
wire   [0:0] select_ln296_5_fu_735_p3;
wire   [47:0] mul_ln296_2_fu_316_p2;
wire   [47:0] add_ln296_4_fu_778_p2;
wire   [0:0] tmp_31_fu_801_p3;
wire   [15:0] bn_out_6_fu_791_p4;
wire   [15:0] zext_ln296_2_fu_817_p1;
wire   [0:0] tmp_33_fu_827_p3;
wire   [0:0] tmp_32_fu_809_p3;
wire   [0:0] xor_ln296_10_fu_835_p2;
wire   [14:0] tmp_9_fu_855_p4;
wire   [15:0] tmp_10_fu_871_p4;
wire   [0:0] icmp_ln296_8_fu_887_p2;
wire   [0:0] tmp_34_fu_847_p3;
wire   [0:0] icmp_ln296_6_fu_865_p2;
wire   [0:0] xor_ln296_11_fu_901_p2;
wire   [0:0] and_ln296_13_fu_907_p2;
wire   [0:0] select_ln296_8_fu_893_p3;
wire   [0:0] xor_ln296_12_fu_921_p2;
wire   [0:0] or_ln296_4_fu_927_p2;
wire   [0:0] xor_ln296_13_fu_933_p2;
wire   [0:0] select_ln296_9_fu_913_p3;
wire   [47:0] mul_ln296_3_fu_320_p2;
wire   [47:0] add_ln296_6_fu_956_p2;
wire   [0:0] tmp_37_fu_979_p3;
wire   [15:0] bn_out_9_fu_969_p4;
wire   [15:0] zext_ln296_3_fu_995_p1;
wire   [0:0] tmp_39_fu_1005_p3;
wire   [0:0] tmp_38_fu_987_p3;
wire   [0:0] xor_ln296_15_fu_1013_p2;
wire   [14:0] tmp_12_fu_1033_p4;
wire   [15:0] tmp_13_fu_1049_p4;
wire   [0:0] icmp_ln296_11_fu_1065_p2;
wire   [0:0] tmp_40_fu_1025_p3;
wire   [0:0] icmp_ln296_9_fu_1043_p2;
wire   [0:0] xor_ln296_16_fu_1079_p2;
wire   [0:0] and_ln296_19_fu_1085_p2;
wire   [0:0] select_ln296_12_fu_1071_p3;
wire   [0:0] xor_ln296_17_fu_1099_p2;
wire   [0:0] or_ln296_6_fu_1105_p2;
wire   [0:0] xor_ln296_18_fu_1111_p2;
wire   [0:0] select_ln296_13_fu_1091_p3;
wire   [0:0] and_ln296_2_fu_1129_p2;
wire   [0:0] or_ln296_8_fu_1133_p2;
wire   [0:0] xor_ln296_4_fu_1138_p2;
wire   [0:0] and_ln296_5_fu_1144_p2;
wire   [0:0] or_ln296_1_fu_1156_p2;
wire   [15:0] select_ln296_2_fu_1149_p3;
wire   [15:0] bn_out_2_fu_1161_p3;
wire   [0:0] tmp_21_fu_1168_p3;
wire   [0:0] and_ln300_fu_1176_p2;
wire   [0:0] and_ln296_8_fu_1190_p2;
wire   [0:0] or_ln296_9_fu_1194_p2;
wire   [0:0] xor_ln296_9_fu_1199_p2;
wire   [0:0] and_ln296_11_fu_1205_p2;
wire   [0:0] or_ln296_3_fu_1217_p2;
wire   [15:0] select_ln296_6_fu_1210_p3;
wire   [15:0] bn_out_5_fu_1222_p3;
wire   [0:0] tmp_29_fu_1229_p3;
wire   [0:0] and_ln300_1_fu_1237_p2;
wire   [0:0] and_ln296_14_fu_1251_p2;
wire   [0:0] or_ln296_10_fu_1255_p2;
wire   [0:0] xor_ln296_14_fu_1260_p2;
wire   [0:0] and_ln296_17_fu_1266_p2;
wire   [0:0] or_ln296_5_fu_1278_p2;
wire   [15:0] select_ln296_10_fu_1271_p3;
wire   [15:0] bn_out_8_fu_1283_p3;
wire   [0:0] tmp_35_fu_1290_p3;
wire   [0:0] and_ln300_2_fu_1298_p2;
wire   [0:0] and_ln296_20_fu_1312_p2;
wire   [0:0] or_ln296_11_fu_1316_p2;
wire   [0:0] xor_ln296_19_fu_1321_p2;
wire   [0:0] and_ln296_23_fu_1327_p2;
wire   [0:0] or_ln296_7_fu_1339_p2;
wire   [15:0] select_ln296_14_fu_1332_p3;
wire   [15:0] bn_out_11_fu_1344_p3;
wire   [0:0] tmp_41_fu_1351_p3;
wire   [0:0] and_ln300_3_fu_1359_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 col_fu_122 = 31'd0;
#0 ap_done_reg = 1'b0;
end

conv_engine_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U1054(
    .din0(acc_buf_q0),
    .din1(mul_ln296_fu_308_p1),
    .dout(mul_ln296_fu_308_p2)
);

conv_engine_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U1055(
    .din0(acc_buf_1_q0),
    .din1(mul_ln296_1_fu_312_p1),
    .dout(mul_ln296_1_fu_312_p2)
);

conv_engine_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U1056(
    .din0(acc_buf_2_q0),
    .din1(mul_ln296_2_fu_316_p1),
    .dout(mul_ln296_2_fu_316_p2)
);

conv_engine_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U1057(
    .din0(acc_buf_3_q0),
    .din1(mul_ln296_3_fu_320_p1),
    .dout(mul_ln296_3_fu_320_p2)
);

conv_engine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln288_fu_392_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_fu_122 <= add_ln288_fu_398_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_122 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln296_10_reg_1533 <= and_ln296_10_fu_767_p2;
        and_ln296_12_reg_1548 <= and_ln296_12_fu_841_p2;
        and_ln296_15_reg_1558 <= and_ln296_15_fu_939_p2;
        and_ln296_16_reg_1564 <= and_ln296_16_fu_945_p2;
        and_ln296_18_reg_1579 <= and_ln296_18_fu_1019_p2;
        and_ln296_21_reg_1589 <= and_ln296_21_fu_1117_p2;
        and_ln296_22_reg_1595 <= and_ln296_22_fu_1123_p2;
        and_ln296_3_reg_1496 <= and_ln296_3_fu_583_p2;
        and_ln296_4_reg_1502 <= and_ln296_4_fu_589_p2;
        and_ln296_6_reg_1517 <= and_ln296_6_fu_663_p2;
        and_ln296_9_reg_1527 <= and_ln296_9_fu_761_p2;
        and_ln296_reg_1486 <= and_ln296_fu_485_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        bn_out_10_reg_1574 <= bn_out_10_fu_999_p2;
        bn_out_1_reg_1481 <= bn_out_1_fu_465_p2;
        bn_out_4_reg_1512 <= bn_out_4_fu_643_p2;
        bn_out_7_reg_1543 <= bn_out_7_fu_821_p2;
        cmp216_24019200_reg_1436 <= cmp216_24019200_fu_368_p2;
        conv7_i_1_cast_reg_1413 <= conv7_i_1_cast_fu_344_p1;
        conv7_i_2_cast_reg_1403 <= conv7_i_2_cast_fu_336_p1;
        conv7_i_3_cast_reg_1393 <= conv7_i_3_cast_fu_328_p1;
        conv7_i_cast_reg_1423 <= conv7_i_cast_fu_352_p1;
        icmp100201_reg_1440 <= icmp100201_fu_374_p2;
        icmp199_reg_1432 <= icmp199_fu_362_p2;
        icmp_ln135_reg_1428 <= icmp_ln135_fu_356_p2;
        icmp_ln296_10_reg_1584 <= icmp_ln296_10_fu_1059_p2;
        icmp_ln296_1_reg_1491 <= icmp_ln296_1_fu_525_p2;
        icmp_ln296_4_reg_1522 <= icmp_ln296_4_fu_703_p2;
        icmp_ln296_7_reg_1553 <= icmp_ln296_7_fu_881_p2;
        sext_ln148_cast_reg_1388 <= sext_ln148_cast_fu_324_p1;
        shl_i_i16_i_1_cast1378_cast_reg_1408 <= shl_i_i16_i_1_cast1378_cast_fu_340_p1;
        shl_i_i16_i_2_cast1380_cast_reg_1398 <= shl_i_i16_i_2_cast1380_cast_fu_332_p1;
        shl_i_i16_i_cast1372_cast_reg_1418 <= shl_i_i16_i_cast1372_cast_fu_348_p1;
        tmp_14_reg_1476 <= add_ln296_fu_422_p2[32'd47];
        tmp_22_reg_1507 <= add_ln296_2_fu_600_p2[32'd47];
        tmp_30_reg_1538 <= add_ln296_4_fu_778_p2[32'd47];
        tmp_36_reg_1569 <= add_ln296_6_fu_956_p2[32'd47];
        zext_ln288_reg_1448[30 : 0] <= zext_ln288_fu_404_p1[30 : 0];
        zext_ln288_reg_1448_pp0_iter1_reg[30 : 0] <= zext_ln288_reg_1448[30 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_buf_1_ce0_local = 1'b1;
    end else begin
        acc_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_buf_2_ce0_local = 1'b1;
    end else begin
        acc_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_buf_3_ce0_local = 1'b1;
    end else begin
        acc_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_buf_ce0_local = 1'b1;
    end else begin
        acc_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln288_fu_392_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_col_5 = 31'd0;
    end else begin
        ap_sig_allocacmp_col_5 = col_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        result_row_1_ce0_local = 1'b1;
    end else begin
        result_row_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp199_reg_1432 == 1'd1))) begin
        result_row_1_we0_local = 1'b1;
    end else begin
        result_row_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        result_row_2_ce0_local = 1'b1;
    end else begin
        result_row_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (cmp216_24019200_reg_1436 == 1'd1))) begin
        result_row_2_we0_local = 1'b1;
    end else begin
        result_row_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        result_row_3_ce0_local = 1'b1;
    end else begin
        result_row_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp100201_reg_1440 == 1'd1))) begin
        result_row_3_we0_local = 1'b1;
    end else begin
        result_row_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        result_row_ce0_local = 1'b1;
    end else begin
        result_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1428 == 1'd1))) begin
        result_row_we0_local = 1'b1;
    end else begin
        result_row_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_buf_1_address0 = zext_ln288_fu_404_p1;

assign acc_buf_1_ce0 = acc_buf_1_ce0_local;

assign acc_buf_2_address0 = zext_ln288_fu_404_p1;

assign acc_buf_2_ce0 = acc_buf_2_ce0_local;

assign acc_buf_3_address0 = zext_ln288_fu_404_p1;

assign acc_buf_3_ce0 = acc_buf_3_ce0_local;

assign acc_buf_address0 = zext_ln288_fu_404_p1;

assign acc_buf_ce0 = acc_buf_ce0_local;

assign add_ln288_fu_398_p2 = (ap_sig_allocacmp_col_5 + 31'd1);

assign add_ln296_2_fu_600_p2 = ($signed(shl_i_i16_i_1_cast1378_cast_reg_1408) + $signed(mul_ln296_1_fu_312_p2));

assign add_ln296_4_fu_778_p2 = ($signed(shl_i_i16_i_2_cast1380_cast_reg_1398) + $signed(mul_ln296_2_fu_316_p2));

assign add_ln296_6_fu_956_p2 = ($signed(sext_ln148_cast_reg_1388) + $signed(mul_ln296_3_fu_320_p2));

assign add_ln296_fu_422_p2 = ($signed(shl_i_i16_i_cast1372_cast_reg_1418) + $signed(mul_ln296_fu_308_p2));

assign and_ln296_10_fu_767_p2 = (tmp_25_fu_649_p3 & select_ln296_5_fu_735_p3);

assign and_ln296_11_fu_1205_p2 = (xor_ln296_9_fu_1199_p2 & tmp_22_reg_1507);

assign and_ln296_12_fu_841_p2 = (xor_ln296_10_fu_835_p2 & tmp_32_fu_809_p3);

assign and_ln296_13_fu_907_p2 = (xor_ln296_11_fu_901_p2 & icmp_ln296_6_fu_865_p2);

assign and_ln296_14_fu_1251_p2 = (icmp_ln296_7_reg_1553 & and_ln296_12_reg_1548);

assign and_ln296_15_fu_939_p2 = (xor_ln296_13_fu_933_p2 & or_ln296_4_fu_927_p2);

assign and_ln296_16_fu_945_p2 = (tmp_33_fu_827_p3 & select_ln296_9_fu_913_p3);

assign and_ln296_17_fu_1266_p2 = (xor_ln296_14_fu_1260_p2 & tmp_30_reg_1538);

assign and_ln296_18_fu_1019_p2 = (xor_ln296_15_fu_1013_p2 & tmp_38_fu_987_p3);

assign and_ln296_19_fu_1085_p2 = (xor_ln296_16_fu_1079_p2 & icmp_ln296_9_fu_1043_p2);

assign and_ln296_1_fu_551_p2 = (xor_ln296_1_fu_545_p2 & icmp_ln296_fu_509_p2);

assign and_ln296_20_fu_1312_p2 = (icmp_ln296_10_reg_1584 & and_ln296_18_reg_1579);

assign and_ln296_21_fu_1117_p2 = (xor_ln296_18_fu_1111_p2 & or_ln296_6_fu_1105_p2);

assign and_ln296_22_fu_1123_p2 = (tmp_39_fu_1005_p3 & select_ln296_13_fu_1091_p3);

assign and_ln296_23_fu_1327_p2 = (xor_ln296_19_fu_1321_p2 & tmp_36_reg_1569);

assign and_ln296_2_fu_1129_p2 = (icmp_ln296_1_reg_1491 & and_ln296_reg_1486);

assign and_ln296_3_fu_583_p2 = (xor_ln296_3_fu_577_p2 & or_ln296_fu_571_p2);

assign and_ln296_4_fu_589_p2 = (tmp_17_fu_471_p3 & select_ln296_1_fu_557_p3);

assign and_ln296_5_fu_1144_p2 = (xor_ln296_4_fu_1138_p2 & tmp_14_reg_1476);

assign and_ln296_6_fu_663_p2 = (xor_ln296_5_fu_657_p2 & tmp_24_fu_631_p3);

assign and_ln296_7_fu_729_p2 = (xor_ln296_6_fu_723_p2 & icmp_ln296_3_fu_687_p2);

assign and_ln296_8_fu_1190_p2 = (icmp_ln296_4_reg_1522 & and_ln296_6_reg_1517);

assign and_ln296_9_fu_761_p2 = (xor_ln296_8_fu_755_p2 & or_ln296_2_fu_749_p2);

assign and_ln296_fu_485_p2 = (xor_ln296_fu_479_p2 & tmp_16_fu_453_p3);

assign and_ln300_1_fu_1237_p2 = (tobool323 & tmp_29_fu_1229_p3);

assign and_ln300_2_fu_1298_p2 = (tobool323 & tmp_35_fu_1290_p3);

assign and_ln300_3_fu_1359_p2 = (tobool323 & tmp_41_fu_1351_p3);

assign and_ln300_fu_1176_p2 = (tobool323 & tmp_21_fu_1168_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bn_out_10_fu_999_p2 = (bn_out_9_fu_969_p4 + zext_ln296_3_fu_995_p1);

assign bn_out_11_fu_1344_p3 = ((or_ln296_7_fu_1339_p2[0:0] == 1'b1) ? select_ln296_14_fu_1332_p3 : bn_out_10_reg_1574);

assign bn_out_1_fu_465_p2 = (bn_out_fu_435_p4 + zext_ln296_fu_461_p1);

assign bn_out_2_fu_1161_p3 = ((or_ln296_1_fu_1156_p2[0:0] == 1'b1) ? select_ln296_2_fu_1149_p3 : bn_out_1_reg_1481);

assign bn_out_3_fu_613_p4 = {{add_ln296_2_fu_600_p2[31:16]}};

assign bn_out_4_fu_643_p2 = (bn_out_3_fu_613_p4 + zext_ln296_1_fu_639_p1);

assign bn_out_5_fu_1222_p3 = ((or_ln296_3_fu_1217_p2[0:0] == 1'b1) ? select_ln296_6_fu_1210_p3 : bn_out_4_reg_1512);

assign bn_out_6_fu_791_p4 = {{add_ln296_4_fu_778_p2[31:16]}};

assign bn_out_7_fu_821_p2 = (bn_out_6_fu_791_p4 + zext_ln296_2_fu_817_p1);

assign bn_out_8_fu_1283_p3 = ((or_ln296_5_fu_1278_p2[0:0] == 1'b1) ? select_ln296_10_fu_1271_p3 : bn_out_7_reg_1543);

assign bn_out_9_fu_969_p4 = {{add_ln296_6_fu_956_p2[31:16]}};

assign bn_out_fu_435_p4 = {{add_ln296_fu_422_p2[31:16]}};

assign cmp216_24019200_fu_368_p2 = (($signed(oc_count) > $signed(32'd2)) ? 1'b1 : 1'b0);

assign conv7_i_1_cast_fu_344_p1 = $signed(conv7_i_1);

assign conv7_i_2_cast_fu_336_p1 = $signed(conv7_i_2);

assign conv7_i_3_cast_fu_328_p1 = $signed(conv7_i_3);

assign conv7_i_cast_fu_352_p1 = $signed(conv7_i);

assign icmp100201_fu_374_p2 = (($signed(empty) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp199_fu_362_p2 = (($signed(empty_54) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_356_p2 = (($signed(oc_count) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln288_fu_392_p2 = (($signed(zext_ln288_1_fu_388_p1) < $signed(out_width)) ? 1'b1 : 1'b0);

assign icmp_ln296_10_fu_1059_p2 = ((tmp_13_fu_1049_p4 == 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln296_11_fu_1065_p2 = ((tmp_13_fu_1049_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln296_1_fu_525_p2 = ((tmp_7_fu_515_p4 == 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln296_2_fu_531_p2 = ((tmp_7_fu_515_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln296_3_fu_687_p2 = ((tmp_s_fu_677_p4 == 15'd32767) ? 1'b1 : 1'b0);

assign icmp_ln296_4_fu_703_p2 = ((tmp_8_fu_693_p4 == 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln296_5_fu_709_p2 = ((tmp_8_fu_693_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln296_6_fu_865_p2 = ((tmp_9_fu_855_p4 == 15'd32767) ? 1'b1 : 1'b0);

assign icmp_ln296_7_fu_881_p2 = ((tmp_10_fu_871_p4 == 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln296_8_fu_887_p2 = ((tmp_10_fu_871_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln296_9_fu_1043_p2 = ((tmp_12_fu_1033_p4 == 15'd32767) ? 1'b1 : 1'b0);

assign icmp_ln296_fu_509_p2 = ((tmp_6_fu_499_p4 == 15'd32767) ? 1'b1 : 1'b0);

assign mul_ln296_1_fu_312_p1 = conv7_i_1_cast_reg_1413;

assign mul_ln296_2_fu_316_p1 = conv7_i_2_cast_reg_1403;

assign mul_ln296_3_fu_320_p1 = conv7_i_3_cast_reg_1393;

assign mul_ln296_fu_308_p1 = conv7_i_cast_reg_1423;

assign or_ln296_10_fu_1255_p2 = (and_ln296_16_reg_1564 | and_ln296_14_fu_1251_p2);

assign or_ln296_11_fu_1316_p2 = (and_ln296_22_reg_1595 | and_ln296_20_fu_1312_p2);

assign or_ln296_1_fu_1156_p2 = (and_ln296_5_fu_1144_p2 | and_ln296_3_reg_1496);

assign or_ln296_2_fu_749_p2 = (xor_ln296_7_fu_743_p2 | tmp_25_fu_649_p3);

assign or_ln296_3_fu_1217_p2 = (and_ln296_9_reg_1527 | and_ln296_11_fu_1205_p2);

assign or_ln296_4_fu_927_p2 = (xor_ln296_12_fu_921_p2 | tmp_33_fu_827_p3);

assign or_ln296_5_fu_1278_p2 = (and_ln296_17_fu_1266_p2 | and_ln296_15_reg_1558);

assign or_ln296_6_fu_1105_p2 = (xor_ln296_17_fu_1099_p2 | tmp_39_fu_1005_p3);

assign or_ln296_7_fu_1339_p2 = (and_ln296_23_fu_1327_p2 | and_ln296_21_reg_1589);

assign or_ln296_8_fu_1133_p2 = (and_ln296_4_reg_1502 | and_ln296_2_fu_1129_p2);

assign or_ln296_9_fu_1194_p2 = (and_ln296_8_fu_1190_p2 | and_ln296_10_reg_1533);

assign or_ln296_fu_571_p2 = (xor_ln296_2_fu_565_p2 | tmp_17_fu_471_p3);

assign relu_out_1_fu_1242_p3 = ((and_ln300_1_fu_1237_p2[0:0] == 1'b1) ? 16'd0 : bn_out_5_fu_1222_p3);

assign relu_out_2_fu_1303_p3 = ((and_ln300_2_fu_1298_p2[0:0] == 1'b1) ? 16'd0 : bn_out_8_fu_1283_p3);

assign relu_out_3_fu_1364_p3 = ((and_ln300_3_fu_1359_p2[0:0] == 1'b1) ? 16'd0 : bn_out_11_fu_1344_p3);

assign relu_out_fu_1181_p3 = ((and_ln300_fu_1176_p2[0:0] == 1'b1) ? 16'd0 : bn_out_2_fu_1161_p3);

assign result_row_1_address0 = zext_ln288_reg_1448_pp0_iter1_reg;

assign result_row_1_ce0 = result_row_1_ce0_local;

assign result_row_1_d0 = relu_out_1_fu_1242_p3;

assign result_row_1_we0 = result_row_1_we0_local;

assign result_row_2_address0 = zext_ln288_reg_1448_pp0_iter1_reg;

assign result_row_2_ce0 = result_row_2_ce0_local;

assign result_row_2_d0 = relu_out_2_fu_1303_p3;

assign result_row_2_we0 = result_row_2_we0_local;

assign result_row_3_address0 = zext_ln288_reg_1448_pp0_iter1_reg;

assign result_row_3_ce0 = result_row_3_ce0_local;

assign result_row_3_d0 = relu_out_3_fu_1364_p3;

assign result_row_3_we0 = result_row_3_we0_local;

assign result_row_address0 = zext_ln288_reg_1448_pp0_iter1_reg;

assign result_row_ce0 = result_row_ce0_local;

assign result_row_d0 = relu_out_fu_1181_p3;

assign result_row_we0 = result_row_we0_local;

assign select_ln296_10_fu_1271_p3 = ((and_ln296_15_reg_1558[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln296_12_fu_1071_p3 = ((and_ln296_18_fu_1019_p2[0:0] == 1'b1) ? icmp_ln296_10_fu_1059_p2 : icmp_ln296_11_fu_1065_p2);

assign select_ln296_13_fu_1091_p3 = ((and_ln296_18_fu_1019_p2[0:0] == 1'b1) ? and_ln296_19_fu_1085_p2 : icmp_ln296_10_fu_1059_p2);

assign select_ln296_14_fu_1332_p3 = ((and_ln296_21_reg_1589[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln296_1_fu_557_p3 = ((and_ln296_fu_485_p2[0:0] == 1'b1) ? and_ln296_1_fu_551_p2 : icmp_ln296_1_fu_525_p2);

assign select_ln296_2_fu_1149_p3 = ((and_ln296_3_reg_1496[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln296_4_fu_715_p3 = ((and_ln296_6_fu_663_p2[0:0] == 1'b1) ? icmp_ln296_4_fu_703_p2 : icmp_ln296_5_fu_709_p2);

assign select_ln296_5_fu_735_p3 = ((and_ln296_6_fu_663_p2[0:0] == 1'b1) ? and_ln296_7_fu_729_p2 : icmp_ln296_4_fu_703_p2);

assign select_ln296_6_fu_1210_p3 = ((and_ln296_9_reg_1527[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln296_8_fu_893_p3 = ((and_ln296_12_fu_841_p2[0:0] == 1'b1) ? icmp_ln296_7_fu_881_p2 : icmp_ln296_8_fu_887_p2);

assign select_ln296_9_fu_913_p3 = ((and_ln296_12_fu_841_p2[0:0] == 1'b1) ? and_ln296_13_fu_907_p2 : icmp_ln296_7_fu_881_p2);

assign select_ln296_fu_537_p3 = ((and_ln296_fu_485_p2[0:0] == 1'b1) ? icmp_ln296_1_fu_525_p2 : icmp_ln296_2_fu_531_p2);

assign sext_ln148_cast_fu_324_p1 = $signed(sext_ln148);

assign shl_i_i16_i_1_cast1378_cast_fu_340_p1 = $signed(shl_i_i16_i_1_cast1378);

assign shl_i_i16_i_2_cast1380_cast_fu_332_p1 = $signed(shl_i_i16_i_2_cast1380);

assign shl_i_i16_i_cast1372_cast_fu_348_p1 = $signed(shl_i_i16_i_cast1372);

assign tmp_10_fu_871_p4 = {{add_ln296_4_fu_778_p2[47:32]}};

assign tmp_12_fu_1033_p4 = {{add_ln296_6_fu_956_p2[47:33]}};

assign tmp_13_fu_1049_p4 = {{add_ln296_6_fu_956_p2[47:32]}};

assign tmp_14_fu_427_p3 = add_ln296_fu_422_p2[32'd47];

assign tmp_15_fu_445_p3 = mul_ln296_fu_308_p2[32'd15];

assign tmp_16_fu_453_p3 = add_ln296_fu_422_p2[32'd31];

assign tmp_17_fu_471_p3 = bn_out_1_fu_465_p2[32'd15];

assign tmp_18_fu_491_p3 = add_ln296_fu_422_p2[32'd32];

assign tmp_21_fu_1168_p3 = bn_out_2_fu_1161_p3[32'd15];

assign tmp_22_fu_605_p3 = add_ln296_2_fu_600_p2[32'd47];

assign tmp_23_fu_623_p3 = mul_ln296_1_fu_312_p2[32'd15];

assign tmp_24_fu_631_p3 = add_ln296_2_fu_600_p2[32'd31];

assign tmp_25_fu_649_p3 = bn_out_4_fu_643_p2[32'd15];

assign tmp_28_fu_669_p3 = add_ln296_2_fu_600_p2[32'd32];

assign tmp_29_fu_1229_p3 = bn_out_5_fu_1222_p3[32'd15];

assign tmp_30_fu_783_p3 = add_ln296_4_fu_778_p2[32'd47];

assign tmp_31_fu_801_p3 = mul_ln296_2_fu_316_p2[32'd15];

assign tmp_32_fu_809_p3 = add_ln296_4_fu_778_p2[32'd31];

assign tmp_33_fu_827_p3 = bn_out_7_fu_821_p2[32'd15];

assign tmp_34_fu_847_p3 = add_ln296_4_fu_778_p2[32'd32];

assign tmp_35_fu_1290_p3 = bn_out_8_fu_1283_p3[32'd15];

assign tmp_36_fu_961_p3 = add_ln296_6_fu_956_p2[32'd47];

assign tmp_37_fu_979_p3 = mul_ln296_3_fu_320_p2[32'd15];

assign tmp_38_fu_987_p3 = add_ln296_6_fu_956_p2[32'd31];

assign tmp_39_fu_1005_p3 = bn_out_10_fu_999_p2[32'd15];

assign tmp_40_fu_1025_p3 = add_ln296_6_fu_956_p2[32'd32];

assign tmp_41_fu_1351_p3 = bn_out_11_fu_1344_p3[32'd15];

assign tmp_6_fu_499_p4 = {{add_ln296_fu_422_p2[47:33]}};

assign tmp_7_fu_515_p4 = {{add_ln296_fu_422_p2[47:32]}};

assign tmp_8_fu_693_p4 = {{add_ln296_2_fu_600_p2[47:32]}};

assign tmp_9_fu_855_p4 = {{add_ln296_4_fu_778_p2[47:33]}};

assign tmp_s_fu_677_p4 = {{add_ln296_2_fu_600_p2[47:33]}};

assign xor_ln296_10_fu_835_p2 = (tmp_33_fu_827_p3 ^ 1'd1);

assign xor_ln296_11_fu_901_p2 = (tmp_34_fu_847_p3 ^ 1'd1);

assign xor_ln296_12_fu_921_p2 = (select_ln296_8_fu_893_p3 ^ 1'd1);

assign xor_ln296_13_fu_933_p2 = (tmp_30_fu_783_p3 ^ 1'd1);

assign xor_ln296_14_fu_1260_p2 = (or_ln296_10_fu_1255_p2 ^ 1'd1);

assign xor_ln296_15_fu_1013_p2 = (tmp_39_fu_1005_p3 ^ 1'd1);

assign xor_ln296_16_fu_1079_p2 = (tmp_40_fu_1025_p3 ^ 1'd1);

assign xor_ln296_17_fu_1099_p2 = (select_ln296_12_fu_1071_p3 ^ 1'd1);

assign xor_ln296_18_fu_1111_p2 = (tmp_36_fu_961_p3 ^ 1'd1);

assign xor_ln296_19_fu_1321_p2 = (or_ln296_11_fu_1316_p2 ^ 1'd1);

assign xor_ln296_1_fu_545_p2 = (tmp_18_fu_491_p3 ^ 1'd1);

assign xor_ln296_2_fu_565_p2 = (select_ln296_fu_537_p3 ^ 1'd1);

assign xor_ln296_3_fu_577_p2 = (tmp_14_fu_427_p3 ^ 1'd1);

assign xor_ln296_4_fu_1138_p2 = (or_ln296_8_fu_1133_p2 ^ 1'd1);

assign xor_ln296_5_fu_657_p2 = (tmp_25_fu_649_p3 ^ 1'd1);

assign xor_ln296_6_fu_723_p2 = (tmp_28_fu_669_p3 ^ 1'd1);

assign xor_ln296_7_fu_743_p2 = (select_ln296_4_fu_715_p3 ^ 1'd1);

assign xor_ln296_8_fu_755_p2 = (tmp_22_fu_605_p3 ^ 1'd1);

assign xor_ln296_9_fu_1199_p2 = (or_ln296_9_fu_1194_p2 ^ 1'd1);

assign xor_ln296_fu_479_p2 = (tmp_17_fu_471_p3 ^ 1'd1);

assign zext_ln288_1_fu_388_p1 = ap_sig_allocacmp_col_5;

assign zext_ln288_fu_404_p1 = ap_sig_allocacmp_col_5;

assign zext_ln296_1_fu_639_p1 = tmp_23_fu_623_p3;

assign zext_ln296_2_fu_817_p1 = tmp_31_fu_801_p3;

assign zext_ln296_3_fu_995_p1 = tmp_37_fu_979_p3;

assign zext_ln296_fu_461_p1 = tmp_15_fu_445_p3;

always @ (posedge ap_clk) begin
    zext_ln288_reg_1448[63:31] <= 33'b000000000000000000000000000000000;
    zext_ln288_reg_1448_pp0_iter1_reg[63:31] <= 33'b000000000000000000000000000000000;
end

endmodule //conv_engine_conv_engine_Pipeline_FINALIZE_COL
