// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv_engine_conv_engine_Pipeline_OUT_COL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        out_width,
        empty_49,
        result_row_address0,
        result_row_ce0,
        result_row_q0,
        output_r,
        empty_50,
        result_row_1_address0,
        result_row_1_ce0,
        result_row_1_q0,
        empty_51,
        result_row_2_address0,
        result_row_2_ce0,
        result_row_2_q0,
        empty_52,
        result_row_3_address0,
        result_row_3_ce0,
        result_row_3_q0,
        oc_count,
        empty_53,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [255:0] m_axi_gmem1_0_WDATA;
output  [31:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [255:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [4:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [31:0] out_width;
input  [62:0] empty_49;
output  [8:0] result_row_address0;
output   result_row_ce0;
input  [15:0] result_row_q0;
input  [63:0] output_r;
input  [62:0] empty_50;
output  [8:0] result_row_1_address0;
output   result_row_1_ce0;
input  [15:0] result_row_1_q0;
input  [62:0] empty_51;
output  [8:0] result_row_2_address0;
output   result_row_2_ce0;
input  [15:0] result_row_2_q0;
input  [62:0] empty_52;
output  [8:0] result_row_3_address0;
output   result_row_3_ce0;
input  [15:0] result_row_3_q0;
input  [31:0] oc_count;
input  [30:0] empty_53;
input  [29:0] empty;

reg ap_idle;
reg m_axi_gmem1_0_AWVALID;
reg[63:0] m_axi_gmem1_0_AWADDR;
reg m_axi_gmem1_0_WVALID;
reg[255:0] m_axi_gmem1_0_WDATA;
reg[31:0] m_axi_gmem1_0_WSTRB;
reg m_axi_gmem1_0_BREADY;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] icmp_ln353_reg_676;
reg   [0:0] icmp210_reg_664;
reg    ap_predicate_op169_write_state4;
reg    ap_block_state4_io_grp4;
reg    ap_block_pp0_stage3_subdone_grp4_done_reg;
reg    ap_block_pp0_stage3_subdone_grp4;
reg    ap_block_pp0_stage3_subdone;
reg   [0:0] cmp216_24019211_reg_668;
reg    ap_predicate_op172_writereq_state4;
reg    ap_block_state4_io_grp5;
reg    ap_block_pp0_stage3_subdone_grp5_done_reg;
reg    ap_block_pp0_stage3_subdone_grp5;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_state72_pp0_stage3_iter17_grp10;
reg    ap_block_pp0_stage3_subdone_grp10_done_reg;
reg    ap_block_pp0_stage3_subdone_grp10;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AW;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg   [0:0] icmp_ln135_reg_660;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    gmem1_blk_n_W;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp2;
reg    ap_block_pp0_stage2_subdone_grp2_done_reg;
reg    ap_block_pp0_stage2_subdone_grp2;
reg    ap_block_pp0_stage2_subdone;
reg    gmem1_blk_n_B;
wire    ap_block_pp0_stage2_grp9;
reg    ap_block_pp0_stage2_subdone_grp9_done_reg;
reg    ap_block_pp0_stage2_subdone_grp9;
wire    ap_block_pp0_stage2_grp3;
reg    ap_block_pp0_stage2_subdone_grp3_done_reg;
reg    ap_block_pp0_stage2_subdone_grp3;
wire    ap_block_pp0_stage3_grp4;
wire    ap_block_pp0_stage3_grp10;
wire    ap_block_pp0_stage3_grp5;
wire    ap_block_pp0_stage0_grp6;
reg    ap_block_pp0_stage0_subdone_grp6_done_reg;
reg    ap_block_pp0_stage0_subdone_grp6;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0_grp11;
reg    ap_block_pp0_stage0_subdone_grp11_done_reg;
reg    ap_block_pp0_stage0_subdone_grp11;
wire    ap_block_pp0_stage0_grp7;
reg   [0:0] icmp100_reg_672;
reg    ap_block_pp0_stage0_subdone_grp7_done_reg;
reg    ap_block_pp0_stage0_subdone_grp7;
wire    ap_block_pp0_stage1_grp8;
reg    ap_block_pp0_stage1_subdone_grp8_done_reg;
reg    ap_block_pp0_stage1_subdone_grp8;
wire    ap_block_pp0_stage1_grp12;
reg    ap_block_pp0_stage1_subdone_grp12_done_reg;
reg    ap_block_pp0_stage1_subdone_grp12;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_state5_io_grp6;
reg    ap_block_state5_io_grp7;
reg    ap_block_state73_pp0_stage0_iter18_grp11;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln135_fu_280_p2;
wire   [0:0] icmp210_fu_286_p2;
wire   [0:0] cmp216_24019211_fu_292_p2;
wire   [0:0] icmp100_fu_298_p2;
wire   [0:0] icmp_ln353_fu_316_p2;
reg   [0:0] icmp_ln353_reg_676_pp0_iter1_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter2_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter3_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter4_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter5_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter6_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter7_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter8_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter9_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter10_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter11_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter12_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter13_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter14_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter15_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter16_reg;
reg   [0:0] icmp_ln353_reg_676_pp0_iter17_reg;
wire   [62:0] zext_ln353_1_fu_336_p1;
reg   [62:0] zext_ln353_1_reg_680;
wire   [4:0] trunc_ln361_fu_360_p1;
reg   [4:0] trunc_ln361_reg_691;
wire   [31:0] shl_ln361_fu_368_p2;
reg   [31:0] shl_ln361_reg_696;
reg   [58:0] trunc_ln361_4_reg_701;
wire   [4:0] trunc_ln361_1_fu_404_p1;
reg   [4:0] trunc_ln361_1_reg_711;
wire   [31:0] shl_ln361_3_fu_412_p2;
reg   [31:0] shl_ln361_3_reg_716;
reg   [58:0] trunc_ln361_5_reg_721;
wire   [255:0] shl_ln361_1_fu_448_p2;
reg   [255:0] shl_ln361_1_reg_736;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    ap_predicate_op140_writereq_state2;
reg    ap_block_state2_io_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
wire   [255:0] shl_ln361_5_fu_479_p2;
reg   [255:0] shl_ln361_5_reg_747;
reg   [15:0] result_row_2_load_reg_752;
reg   [15:0] result_row_3_load_reg_757;
reg    ap_predicate_op151_writereq_state3;
reg    ap_block_state3_io_grp3;
reg    ap_block_pp0_stage2_11001_grp3;
wire   [31:0] shl_ln361_7_fu_523_p2;
reg   [31:0] shl_ln361_7_reg_768;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
wire   [255:0] shl_ln361_9_fu_541_p2;
reg   [255:0] shl_ln361_9_reg_773;
reg   [58:0] trunc_ln361_6_reg_778;
wire   [4:0] trunc_ln361_3_fu_574_p1;
reg   [4:0] trunc_ln361_3_reg_783;
reg   [58:0] trunc_ln361_7_reg_789;
reg    ap_block_pp0_stage3_11001_grp5;
wire   [31:0] shl_ln361_11_fu_604_p2;
reg   [31:0] shl_ln361_11_reg_800;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
wire   [255:0] shl_ln361_13_fu_621_p2;
reg   [255:0] shl_ln361_13_reg_805;
reg    ap_block_pp0_stage0_11001_grp7;
reg    ap_block_state6_io_grp8;
reg    ap_block_state74_pp0_stage1_iter18_grp12;
wire   [63:0] zext_ln353_fu_328_p1;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln361_fu_454_p1;
wire  signed [63:0] sext_ln361_1_fu_485_p1;
wire  signed [63:0] sext_ln361_2_fu_588_p1;
wire  signed [63:0] sext_ln361_3_fu_627_p1;
reg    ap_block_state71_pp0_stage2_iter17_grp9;
reg    ap_block_pp0_stage2_11001_grp9;
reg    ap_predicate_op148_write_state3;
reg    ap_block_state3_io_grp2;
reg    ap_block_pp0_stage2_11001_grp2;
wire    ap_block_pp0_stage2_01001_grp2;
reg    ap_block_pp0_stage3_11001_grp10;
reg    ap_block_pp0_stage3_11001_grp4;
wire    ap_block_pp0_stage3_01001_grp4;
reg    ap_block_pp0_stage0_11001_grp11;
reg    ap_block_pp0_stage0_11001_grp6;
wire    ap_block_pp0_stage0_01001_grp6;
reg    ap_block_pp0_stage1_11001_grp12;
reg    ap_block_pp0_stage1_11001_grp8;
wire    ap_block_pp0_stage1_01001_grp8;
reg   [30:0] col_2_fu_110;
wire   [30:0] add_ln353_fu_322_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_col;
reg    result_row_ce0_local;
reg    result_row_1_ce0_local;
reg    result_row_2_ce0_local;
reg    result_row_3_ce0_local;
wire   [31:0] zext_ln353_2_fu_312_p1;
wire   [62:0] add_ln361_4_fu_340_p2;
wire   [63:0] shl_ln5_fu_346_p3;
wire   [63:0] add_ln361_fu_354_p2;
wire   [31:0] zext_ln361_1_fu_364_p1;
wire   [62:0] add_ln361_5_fu_384_p2;
wire   [63:0] shl_ln361_4_fu_390_p3;
wire   [63:0] add_ln361_1_fu_398_p2;
wire   [31:0] zext_ln361_4_fu_408_p1;
wire    ap_block_pp0_stage1_grp0;
wire   [7:0] shl_ln361_2_fu_437_p3;
wire   [255:0] zext_ln361_fu_433_p1;
wire   [255:0] zext_ln361_2_fu_444_p1;
wire   [7:0] shl_ln361_6_fu_468_p3;
wire   [255:0] zext_ln361_3_fu_464_p1;
wire   [255:0] zext_ln361_5_fu_475_p1;
wire    ap_block_pp0_stage2_grp0;
wire   [62:0] add_ln361_6_fu_495_p2;
wire   [63:0] shl_ln361_8_fu_499_p3;
wire   [63:0] add_ln361_2_fu_507_p2;
wire   [4:0] trunc_ln361_2_fu_515_p1;
wire   [31:0] zext_ln361_7_fu_519_p1;
wire   [7:0] shl_ln361_s_fu_529_p3;
wire   [255:0] zext_ln361_6_fu_512_p1;
wire   [255:0] zext_ln361_8_fu_537_p1;
wire   [62:0] add_ln361_7_fu_557_p2;
wire   [63:0] shl_ln361_10_fu_561_p3;
wire   [63:0] add_ln361_3_fu_569_p2;
wire    ap_block_pp0_stage3_grp0;
wire   [31:0] zext_ln361_10_fu_601_p1;
wire   [7:0] shl_ln361_12_fu_610_p3;
wire   [255:0] zext_ln361_9_fu_598_p1;
wire   [255:0] zext_ln361_11_fu_617_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage3_11001;
reg    ap_condition_exit_pp0_iter17_stage1;
reg    ap_idle_pp0_0to16;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to18;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp5_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp10_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp9_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp11_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp7_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp8_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp12_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 col_2_fu_110 = 31'd0;
#0 ap_done_reg = 1'b0;
end

conv_engine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp11_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp11_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp11)) begin
                ap_block_pp0_stage0_subdone_grp11_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp6)) begin
                ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp7)) begin
                ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp12_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp12_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp12)) begin
                ap_block_pp0_stage1_subdone_grp12_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp8_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp8_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp8)) begin
                ap_block_pp0_stage1_subdone_grp8_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp2)) begin
                ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp3)) begin
                ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp9_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp9_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp9)) begin
                ap_block_pp0_stage2_subdone_grp9_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp10_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp10_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp10)) begin
                ap_block_pp0_stage3_subdone_grp10_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp4)) begin
                ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp5)) begin
                ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter18 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln353_fu_316_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_2_fu_110 <= add_ln353_fu_322_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_2_fu_110 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cmp216_24019211_reg_668 <= cmp216_24019211_fu_292_p2;
        icmp100_reg_672 <= icmp100_fu_298_p2;
        icmp210_reg_664 <= icmp210_fu_286_p2;
        icmp_ln135_reg_660 <= icmp_ln135_fu_280_p2;
        icmp_ln353_reg_676 <= icmp_ln353_fu_316_p2;
        icmp_ln353_reg_676_pp0_iter10_reg <= icmp_ln353_reg_676_pp0_iter9_reg;
        icmp_ln353_reg_676_pp0_iter11_reg <= icmp_ln353_reg_676_pp0_iter10_reg;
        icmp_ln353_reg_676_pp0_iter12_reg <= icmp_ln353_reg_676_pp0_iter11_reg;
        icmp_ln353_reg_676_pp0_iter13_reg <= icmp_ln353_reg_676_pp0_iter12_reg;
        icmp_ln353_reg_676_pp0_iter14_reg <= icmp_ln353_reg_676_pp0_iter13_reg;
        icmp_ln353_reg_676_pp0_iter15_reg <= icmp_ln353_reg_676_pp0_iter14_reg;
        icmp_ln353_reg_676_pp0_iter16_reg <= icmp_ln353_reg_676_pp0_iter15_reg;
        icmp_ln353_reg_676_pp0_iter17_reg <= icmp_ln353_reg_676_pp0_iter16_reg;
        icmp_ln353_reg_676_pp0_iter1_reg <= icmp_ln353_reg_676;
        icmp_ln353_reg_676_pp0_iter2_reg <= icmp_ln353_reg_676_pp0_iter1_reg;
        icmp_ln353_reg_676_pp0_iter3_reg <= icmp_ln353_reg_676_pp0_iter2_reg;
        icmp_ln353_reg_676_pp0_iter4_reg <= icmp_ln353_reg_676_pp0_iter3_reg;
        icmp_ln353_reg_676_pp0_iter5_reg <= icmp_ln353_reg_676_pp0_iter4_reg;
        icmp_ln353_reg_676_pp0_iter6_reg <= icmp_ln353_reg_676_pp0_iter5_reg;
        icmp_ln353_reg_676_pp0_iter7_reg <= icmp_ln353_reg_676_pp0_iter6_reg;
        icmp_ln353_reg_676_pp0_iter8_reg <= icmp_ln353_reg_676_pp0_iter7_reg;
        icmp_ln353_reg_676_pp0_iter9_reg <= icmp_ln353_reg_676_pp0_iter8_reg;
        shl_ln361_3_reg_716 <= shl_ln361_3_fu_412_p2;
        shl_ln361_reg_696 <= shl_ln361_fu_368_p2;
        trunc_ln361_1_reg_711 <= trunc_ln361_1_fu_404_p1;
        trunc_ln361_4_reg_701 <= {{add_ln361_fu_354_p2[63:5]}};
        trunc_ln361_5_reg_721 <= {{add_ln361_1_fu_398_p2[63:5]}};
        trunc_ln361_reg_691 <= trunc_ln361_fu_360_p1;
        zext_ln353_1_reg_680[30 : 0] <= zext_ln353_1_fu_336_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        result_row_2_load_reg_752 <= result_row_2_q0;
        result_row_3_load_reg_757 <= result_row_3_q0;
        shl_ln361_1_reg_736 <= shl_ln361_1_fu_448_p2;
        shl_ln361_5_reg_747 <= shl_ln361_5_fu_479_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        shl_ln361_11_reg_800 <= shl_ln361_11_fu_604_p2;
        shl_ln361_13_reg_805 <= shl_ln361_13_fu_621_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        shl_ln361_7_reg_768 <= shl_ln361_7_fu_523_p2;
        shl_ln361_9_reg_773 <= shl_ln361_9_fu_541_p2;
        trunc_ln361_3_reg_783 <= trunc_ln361_3_fu_574_p1;
        trunc_ln361_6_reg_778 <= {{add_ln361_2_fu_507_p2[63:5]}};
        trunc_ln361_7_reg_789 <= {{add_ln361_3_fu_569_p2[63:5]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (icmp_ln353_reg_676 == 1'd0))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln353_reg_676_pp0_iter17_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter17_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter17_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready == 1'b0) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter16_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to16 = 1'b1;
    end else begin
        ap_idle_pp0_0to16 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to18 = 1'b1;
    end else begin
        ap_idle_pp0_1to18 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_col = 31'd0;
    end else begin
        ap_sig_allocacmp_col = col_2_fu_110;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op172_writereq_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)) | ((icmp100_reg_672 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg) & (1'b0 == ap_block_pp0_stage0_grp7)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage2_grp3) & (icmp210_reg_664 == 1'd1) & (icmp_ln353_reg_676 == 1'd1)) | ((icmp_ln135_reg_660 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1) & (icmp_ln353_reg_676 == 1'd1)))) begin
        gmem1_blk_n_AW = m_axi_gmem1_0_AWREADY;
    end else begin
        gmem1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp100_reg_672 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp12_done_reg) & (1'b0 == ap_block_pp0_stage1_grp12)) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (cmp216_24019211_reg_668 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg) & (1'b0 == ap_block_pp0_stage0_grp11)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp10) & (1'b0 == ap_block_pp0_stage3_subdone_grp10_done_reg) & (icmp210_reg_664 == 1'd1)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln135_reg_660 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp9_done_reg) & (1'b0 == ap_block_pp0_stage2_grp9)))) begin
        gmem1_blk_n_B = m_axi_gmem1_0_BVALID;
    end else begin
        gmem1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg) & (ap_predicate_op169_write_state4 == 1'b1)) | ((icmp100_reg_672 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp8_done_reg) & (1'b0 == ap_block_pp0_stage1_grp8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (cmp216_24019211_reg_668 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg) & (1'b0 == ap_block_pp0_stage0_grp6)) | ((icmp_ln135_reg_660 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage2_grp2) & (icmp_ln353_reg_676 == 1'd1)))) begin
        gmem1_blk_n_W = m_axi_gmem1_0_WREADY;
    end else begin
        gmem1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((icmp100_reg_672 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg))) begin
        m_axi_gmem1_0_AWADDR = sext_ln361_3_fu_627_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op172_writereq_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg))) begin
        m_axi_gmem1_0_AWADDR = sext_ln361_2_fu_588_p1;
    end else if (((ap_predicate_op151_writereq_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg))) begin
        m_axi_gmem1_0_AWADDR = sext_ln361_1_fu_485_p1;
    end else if (((ap_predicate_op140_writereq_state2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg))) begin
        m_axi_gmem1_0_AWADDR = sext_ln361_fu_454_p1;
    end else begin
        m_axi_gmem1_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op172_writereq_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)) | ((ap_predicate_op151_writereq_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg)) | ((ap_predicate_op140_writereq_state2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)) | ((icmp100_reg_672 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)))) begin
        m_axi_gmem1_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp100_reg_672 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp12) & (1'b0 == ap_block_pp0_stage1_subdone_grp12_done_reg)) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (cmp216_24019211_reg_668 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp10) & (1'b0 == ap_block_pp0_stage3_subdone_grp10_done_reg) & (icmp210_reg_664 == 1'd1)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln135_reg_660 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp9) & (1'b0 == ap_block_pp0_stage2_subdone_grp9_done_reg)))) begin
        m_axi_gmem1_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem1_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp100_reg_672 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001_grp8) & (1'b0 == ap_block_pp0_stage1_subdone_grp8_done_reg))) begin
        m_axi_gmem1_0_WDATA = shl_ln361_13_reg_805;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (cmp216_24019211_reg_668 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg))) begin
        m_axi_gmem1_0_WDATA = shl_ln361_9_reg_773;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg) & (ap_predicate_op169_write_state4 == 1'b1))) begin
        m_axi_gmem1_0_WDATA = shl_ln361_5_reg_747;
    end else if (((ap_predicate_op148_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_01001_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg))) begin
        m_axi_gmem1_0_WDATA = shl_ln361_1_reg_736;
    end else begin
        m_axi_gmem1_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((icmp100_reg_672 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001_grp8) & (1'b0 == ap_block_pp0_stage1_subdone_grp8_done_reg))) begin
        m_axi_gmem1_0_WSTRB = shl_ln361_11_reg_800;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (cmp216_24019211_reg_668 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg))) begin
        m_axi_gmem1_0_WSTRB = shl_ln361_7_reg_768;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg) & (ap_predicate_op169_write_state4 == 1'b1))) begin
        m_axi_gmem1_0_WSTRB = shl_ln361_3_reg_716;
    end else if (((ap_predicate_op148_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_01001_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg))) begin
        m_axi_gmem1_0_WSTRB = shl_ln361_reg_696;
    end else begin
        m_axi_gmem1_0_WSTRB = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg) & (ap_predicate_op169_write_state4 == 1'b1)) | ((ap_predicate_op148_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg)) | ((icmp100_reg_672 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp8) & (1'b0 == ap_block_pp0_stage1_subdone_grp8_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (cmp216_24019211_reg_668 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)))) begin
        m_axi_gmem1_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        result_row_1_ce0_local = 1'b1;
    end else begin
        result_row_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        result_row_2_ce0_local = 1'b1;
    end else begin
        result_row_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        result_row_3_ce0_local = 1'b1;
    end else begin
        result_row_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        result_row_ce0_local = 1'b1;
    end else begin
        result_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to18 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter17_stage1) & (ap_idle_pp0_0to16 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln353_fu_322_p2 = (ap_sig_allocacmp_col + 31'd1);

assign add_ln361_1_fu_398_p2 = (shl_ln361_4_fu_390_p3 + output_r);

assign add_ln361_2_fu_507_p2 = (shl_ln361_8_fu_499_p3 + output_r);

assign add_ln361_3_fu_569_p2 = (shl_ln361_10_fu_561_p3 + output_r);

assign add_ln361_4_fu_340_p2 = (zext_ln353_1_fu_336_p1 + empty_49);

assign add_ln361_5_fu_384_p2 = (zext_ln353_1_fu_336_p1 + empty_50);

assign add_ln361_6_fu_495_p2 = (zext_ln353_1_reg_680 + empty_51);

assign add_ln361_7_fu_557_p2 = (zext_ln353_1_reg_680 + empty_52);

assign add_ln361_fu_354_p2 = (shl_ln5_fu_346_p3 + output_r);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state73_pp0_stage0_iter18_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b1 == ap_block_state5_io_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)) | ((1'b1 == ap_block_state5_io_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)))));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp11 = ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state73_pp0_stage0_iter18_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp6 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp7 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg));
end

assign ap_block_pp0_stage0_grp11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state73_pp0_stage0_iter18_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b1 == ap_block_state5_io_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)) | ((1'b1 == ap_block_state5_io_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)))));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp11 = ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state73_pp0_stage0_iter18_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp6 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp7 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg));
end

assign ap_block_pp0_stage1_01001_grp8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp12 = ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state74_pp0_stage1_iter18_grp12) & (1'b0 == ap_block_pp0_stage1_subdone_grp12_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io_grp8) & (1'b0 == ap_block_pp0_stage1_subdone_grp8_done_reg));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state74_pp0_stage1_iter18_grp12) & (1'b0 == ap_block_pp0_stage1_subdone_grp12_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io_grp8) & (1'b0 == ap_block_pp0_stage1_subdone_grp8_done_reg)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp12 = ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state74_pp0_stage1_iter18_grp12) & (1'b0 == ap_block_pp0_stage1_subdone_grp12_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io_grp8) & (1'b0 == ap_block_pp0_stage1_subdone_grp8_done_reg));
end

assign ap_block_pp0_stage2_01001_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((1'b1 == ap_block_state3_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp3 = ((1'b1 == ap_block_state3_io_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp9 = ((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state71_pp0_stage2_iter17_grp9) & (1'b0 == ap_block_pp0_stage2_subdone_grp9_done_reg));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state71_pp0_stage2_iter17_grp9) & (1'b0 == ap_block_pp0_stage2_subdone_grp9_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state3_io_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state3_io_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg)))));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp2 = ((1'b1 == ap_block_state3_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp3 = ((1'b1 == ap_block_state3_io_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp9 = ((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state71_pp0_stage2_iter17_grp9) & (1'b0 == ap_block_pp0_stage2_subdone_grp9_done_reg));
end

assign ap_block_pp0_stage3_01001_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state72_pp0_stage3_iter17_grp10) & (1'b0 == ap_block_pp0_stage3_subdone_grp10_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state4_io_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state4_io_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)))));
end

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp10 = ((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state72_pp0_stage3_iter17_grp10) & (1'b0 == ap_block_pp0_stage3_subdone_grp10_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp4 = ((1'b1 == ap_block_state4_io_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp5 = ((1'b1 == ap_block_state4_io_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg));
end

assign ap_block_pp0_stage3_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state72_pp0_stage3_iter17_grp10) & (1'b0 == ap_block_pp0_stage3_subdone_grp10_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state4_io_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state4_io_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)))));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp10 = ((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state72_pp0_stage3_iter17_grp10) & (1'b0 == ap_block_pp0_stage3_subdone_grp10_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp4 = ((1'b1 == ap_block_state4_io_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp5 = ((1'b1 == ap_block_state4_io_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((m_axi_gmem1_0_AWREADY == 1'b0) & (ap_predicate_op140_writereq_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_io_grp2 = ((ap_predicate_op148_write_state3 == 1'b1) & (m_axi_gmem1_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_io_grp3 = ((m_axi_gmem1_0_AWREADY == 1'b0) & (ap_predicate_op151_writereq_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_io_grp4 = ((ap_predicate_op169_write_state4 == 1'b1) & (m_axi_gmem1_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_io_grp5 = ((m_axi_gmem1_0_AWREADY == 1'b0) & (ap_predicate_op172_writereq_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state5_io_grp6 = ((cmp216_24019211_reg_668 == 1'd1) & (m_axi_gmem1_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_io_grp7 = ((m_axi_gmem1_0_AWREADY == 1'b0) & (icmp100_reg_672 == 1'd1));
end

always @ (*) begin
    ap_block_state6_io_grp8 = ((icmp100_reg_672 == 1'd1) & (m_axi_gmem1_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state71_pp0_stage2_iter17_grp9 = ((icmp_ln135_reg_660 == 1'd1) & (m_axi_gmem1_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state72_pp0_stage3_iter17_grp10 = ((icmp210_reg_664 == 1'd1) & (m_axi_gmem1_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state73_pp0_stage0_iter18_grp11 = ((cmp216_24019211_reg_668 == 1'd1) & (m_axi_gmem1_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state74_pp0_stage1_iter18_grp12 = ((icmp100_reg_672 == 1'd1) & (m_axi_gmem1_0_BVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

always @ (*) begin
    ap_predicate_op140_writereq_state2 = ((icmp_ln135_reg_660 == 1'd1) & (icmp_ln353_reg_676 == 1'd1));
end

always @ (*) begin
    ap_predicate_op148_write_state3 = ((icmp_ln135_reg_660 == 1'd1) & (icmp_ln353_reg_676 == 1'd1));
end

always @ (*) begin
    ap_predicate_op151_writereq_state3 = ((icmp210_reg_664 == 1'd1) & (icmp_ln353_reg_676 == 1'd1));
end

always @ (*) begin
    ap_predicate_op169_write_state4 = ((icmp210_reg_664 == 1'd1) & (icmp_ln353_reg_676 == 1'd1));
end

always @ (*) begin
    ap_predicate_op172_writereq_state4 = ((cmp216_24019211_reg_668 == 1'd1) & (icmp_ln353_reg_676 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign cmp216_24019211_fu_292_p2 = (($signed(oc_count) > $signed(32'd2)) ? 1'b1 : 1'b0);

assign icmp100_fu_298_p2 = (($signed(empty) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp210_fu_286_p2 = (($signed(empty_53) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_280_p2 = (($signed(oc_count) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln353_fu_316_p2 = (($signed(zext_ln353_2_fu_312_p1) < $signed(out_width)) ? 1'b1 : 1'b0);

assign m_axi_gmem1_0_ARADDR = 64'd0;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 32'd0;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_ARVALID = 1'b0;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = 64'd1;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_RREADY = 1'b0;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign result_row_1_address0 = zext_ln353_fu_328_p1;

assign result_row_1_ce0 = result_row_1_ce0_local;

assign result_row_2_address0 = zext_ln353_fu_328_p1;

assign result_row_2_ce0 = result_row_2_ce0_local;

assign result_row_3_address0 = zext_ln353_fu_328_p1;

assign result_row_3_ce0 = result_row_3_ce0_local;

assign result_row_address0 = zext_ln353_fu_328_p1;

assign result_row_ce0 = result_row_ce0_local;

assign sext_ln361_1_fu_485_p1 = $signed(trunc_ln361_5_reg_721);

assign sext_ln361_2_fu_588_p1 = $signed(trunc_ln361_6_reg_778);

assign sext_ln361_3_fu_627_p1 = $signed(trunc_ln361_7_reg_789);

assign sext_ln361_fu_454_p1 = $signed(trunc_ln361_4_reg_701);

assign shl_ln361_10_fu_561_p3 = {{add_ln361_7_fu_557_p2}, {1'd0}};

assign shl_ln361_11_fu_604_p2 = 32'd3 << zext_ln361_10_fu_601_p1;

assign shl_ln361_12_fu_610_p3 = {{trunc_ln361_3_reg_783}, {3'd0}};

assign shl_ln361_13_fu_621_p2 = zext_ln361_9_fu_598_p1 << zext_ln361_11_fu_617_p1;

assign shl_ln361_1_fu_448_p2 = zext_ln361_fu_433_p1 << zext_ln361_2_fu_444_p1;

assign shl_ln361_2_fu_437_p3 = {{trunc_ln361_reg_691}, {3'd0}};

assign shl_ln361_3_fu_412_p2 = 32'd3 << zext_ln361_4_fu_408_p1;

assign shl_ln361_4_fu_390_p3 = {{add_ln361_5_fu_384_p2}, {1'd0}};

assign shl_ln361_5_fu_479_p2 = zext_ln361_3_fu_464_p1 << zext_ln361_5_fu_475_p1;

assign shl_ln361_6_fu_468_p3 = {{trunc_ln361_1_reg_711}, {3'd0}};

assign shl_ln361_7_fu_523_p2 = 32'd3 << zext_ln361_7_fu_519_p1;

assign shl_ln361_8_fu_499_p3 = {{add_ln361_6_fu_495_p2}, {1'd0}};

assign shl_ln361_9_fu_541_p2 = zext_ln361_6_fu_512_p1 << zext_ln361_8_fu_537_p1;

assign shl_ln361_fu_368_p2 = 32'd3 << zext_ln361_1_fu_364_p1;

assign shl_ln361_s_fu_529_p3 = {{trunc_ln361_2_fu_515_p1}, {3'd0}};

assign shl_ln5_fu_346_p3 = {{add_ln361_4_fu_340_p2}, {1'd0}};

assign trunc_ln361_1_fu_404_p1 = add_ln361_1_fu_398_p2[4:0];

assign trunc_ln361_2_fu_515_p1 = add_ln361_2_fu_507_p2[4:0];

assign trunc_ln361_3_fu_574_p1 = add_ln361_3_fu_569_p2[4:0];

assign trunc_ln361_fu_360_p1 = add_ln361_fu_354_p2[4:0];

assign zext_ln353_1_fu_336_p1 = ap_sig_allocacmp_col;

assign zext_ln353_2_fu_312_p1 = ap_sig_allocacmp_col;

assign zext_ln353_fu_328_p1 = ap_sig_allocacmp_col;

assign zext_ln361_10_fu_601_p1 = trunc_ln361_3_reg_783;

assign zext_ln361_11_fu_617_p1 = shl_ln361_12_fu_610_p3;

assign zext_ln361_1_fu_364_p1 = trunc_ln361_fu_360_p1;

assign zext_ln361_2_fu_444_p1 = shl_ln361_2_fu_437_p3;

assign zext_ln361_3_fu_464_p1 = result_row_1_q0;

assign zext_ln361_4_fu_408_p1 = trunc_ln361_1_fu_404_p1;

assign zext_ln361_5_fu_475_p1 = shl_ln361_6_fu_468_p3;

assign zext_ln361_6_fu_512_p1 = result_row_2_load_reg_752;

assign zext_ln361_7_fu_519_p1 = trunc_ln361_2_fu_515_p1;

assign zext_ln361_8_fu_537_p1 = shl_ln361_s_fu_529_p3;

assign zext_ln361_9_fu_598_p1 = result_row_3_load_reg_757;

assign zext_ln361_fu_433_p1 = result_row_q0;

always @ (posedge ap_clk) begin
    zext_ln353_1_reg_680[62:31] <= 32'b00000000000000000000000000000000;
end

endmodule //conv_engine_conv_engine_Pipeline_OUT_COL
