# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/researchadmin/ConvBlock/ConvBlock.srcs/sources_1/bd/tinyyolo_zcu102/ip/tinyyolo_zcu102_rst_ps8_0_99M_0/tinyyolo_zcu102_rst_ps8_0_99M_0.xci
# IP: The module: 'tinyyolo_zcu102_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/tinyyolo_zcu102/ip/tinyyolo_zcu102_rst_ps8_0_99M_0/tinyyolo_zcu102_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tinyyolo_zcu102_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/tinyyolo_zcu102/ip/tinyyolo_zcu102_rst_ps8_0_99M_0/tinyyolo_zcu102_rst_ps8_0_99M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tinyyolo_zcu102_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/tinyyolo_zcu102/ip/tinyyolo_zcu102_rst_ps8_0_99M_0/tinyyolo_zcu102_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tinyyolo_zcu102_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/researchadmin/ConvBlock/ConvBlock.srcs/sources_1/bd/tinyyolo_zcu102/ip/tinyyolo_zcu102_rst_ps8_0_99M_0/tinyyolo_zcu102_rst_ps8_0_99M_0.xci
# IP: The module: 'tinyyolo_zcu102_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/tinyyolo_zcu102/ip/tinyyolo_zcu102_rst_ps8_0_99M_0/tinyyolo_zcu102_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tinyyolo_zcu102_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/tinyyolo_zcu102/ip/tinyyolo_zcu102_rst_ps8_0_99M_0/tinyyolo_zcu102_rst_ps8_0_99M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tinyyolo_zcu102_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/tinyyolo_zcu102/ip/tinyyolo_zcu102_rst_ps8_0_99M_0/tinyyolo_zcu102_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tinyyolo_zcu102_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
