# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Redesign/Redesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign || ORIG_REF_NAME==Redesign} -quiet] -quiet

# IP: bd/Redesign/ip/Redesign_conv_engine_1_0/Redesign_conv_engine_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign_conv_engine_1_0 || ORIG_REF_NAME==Redesign_conv_engine_1_0} -quiet] -quiet

# IP: bd/Redesign/ip/Redesign_rst_ps8_0_99M_0/Redesign_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign_rst_ps8_0_99M_0 || ORIG_REF_NAME==Redesign_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/Redesign/ip/Redesign_zynq_ultra_ps_e_0_0/Redesign_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Redesign_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Redesign/ip/Redesign_smartconnect_0_2/Redesign_smartconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign_smartconnect_0_2 || ORIG_REF_NAME==Redesign_smartconnect_0_2} -quiet] -quiet

# IP: bd/Redesign/ip/Redesign_smartconnect_0_3/Redesign_smartconnect_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign_smartconnect_0_3 || ORIG_REF_NAME==Redesign_smartconnect_0_3} -quiet] -quiet

# IP: bd/Redesign/ip/Redesign_smartconnect_0_4/Redesign_smartconnect_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign_smartconnect_0_4 || ORIG_REF_NAME==Redesign_smartconnect_0_4} -quiet] -quiet

# IP: bd/Redesign/ip/Redesign_smartconnect_0_5/Redesign_smartconnect_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign_smartconnect_0_5 || ORIG_REF_NAME==Redesign_smartconnect_0_5} -quiet] -quiet

# IP: bd/Redesign/ip/Redesign_smartconnect_0_6/Redesign_smartconnect_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Redesign_smartconnect_0_6 || ORIG_REF_NAME==Redesign_smartconnect_0_6} -quiet] -quiet

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/Redesign_ooc.xdc
