# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/researchadmin/ConvBlock/ConvBlock.runs/synth_1/Redesign_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param bd.open.in_stealth_mode 2
set_param chipscope.maxJobs 8
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/researchadmin/ConvBlock/ConvBlock.cache/wt [current_project]
set_property parent.project_path /home/researchadmin/ConvBlock/ConvBlock.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.4 [current_project]
set_property ip_repo_paths {
  /home/researchadmin/korino/arm/hls/conv_engine_hls/solution1/impl
  /home/researchadmin/korino/arm/hls/9feb/tinyyolo_zcu102/solution1/impl
  /home/researchadmin/korino/arm/hls/11feb/tinyyolo_zcu102/solution1/impl/ip
  /home/researchadmin/korino/arm/hls/13feb/tinyyolo_zcu102/solution1/impl/ip
  /home/researchadmin/korino/arm/hls/16feb/tinyyolo_zcu102/solution1/impl/ip
  /home/researchadmin/korino/arm/hls/16feb/tinyyolo_zcu102_v3/solution1/impl/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/researchadmin/ConvBlock/ConvBlock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/hdl/Redesign_wrapper.v
add_files /home/researchadmin/ConvBlock/ConvBlock.srcs/sources_1/bd/Redesign/Redesign.bd
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_conv_engine_1_0/constraints/conv_engine_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_rst_ps8_0_99M_0/Redesign_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_rst_ps8_0_99M_0/Redesign_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_rst_ps8_0_99M_0/Redesign_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_zynq_ultra_ps_e_0_0/Redesign_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_zynq_ultra_ps_e_0_0/Redesign_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_2/bd_0/ip/ip_1/bd_6f26_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_2/bd_0/ip/ip_1/bd_6f26_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_2/bd_0/ip/ip_5/bd_6f26_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_2/bd_0/ip/ip_6/bd_6f26_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_2/bd_0/ip/ip_7/bd_6f26_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_2/bd_0/ip/ip_8/bd_6f26_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_2/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_2/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_1/bd_afe7_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_1/bd_afe7_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_5/bd_afe7_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_6/bd_afe7_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_7/bd_afe7_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_8/bd_afe7_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_9/bd_afe7_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_10/bd_afe7_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/bd_0/ip/ip_11/bd_afe7_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_3/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_4/bd_0/ip/ip_1/bd_6da6_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_4/bd_0/ip/ip_1/bd_6da6_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_4/bd_0/ip/ip_5/bd_6da6_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_4/bd_0/ip/ip_6/bd_6da6_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_4/bd_0/ip/ip_7/bd_6da6_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_4/bd_0/ip/ip_8/bd_6da6_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_4/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_4/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_5/bd_0/ip/ip_1/bd_ad67_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_5/bd_0/ip/ip_1/bd_ad67_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_5/bd_0/ip/ip_5/bd_ad67_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_5/bd_0/ip/ip_6/bd_ad67_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_5/bd_0/ip/ip_7/bd_ad67_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_5/bd_0/ip/ip_8/bd_ad67_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_5/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_5/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_1/bd_ac27_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_1/bd_ac27_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_5/bd_ac27_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_6/bd_ac27_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_7/bd_ac27_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_8/bd_ac27_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_9/bd_ac27_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_10/bd_ac27_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/bd_0/ip/ip_11/bd_ac27_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_6/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/Redesign_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/researchadmin/ConvBlock/ConvBlock.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Redesign_wrapper -part xczu9eg-ffvb1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Redesign_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Redesign_wrapper_utilization_synth.rpt -pb Redesign_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
