# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/researchadmin/ConvBlock/ConvBlock.srcs/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/Redesign_smartconnect_0_1.xci
# IP: The module: 'Redesign_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/bd_6e66.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_0/bd_6e66_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_1/bd_6e66_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_2/bd_6e66_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_3/bd_6e66_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_4/bd_6e66_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_5/bd_6e66_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_6/bd_6e66_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_7/bd_6e66_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_8/bd_6e66_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_9/bd_6e66_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_10/bd_6e66_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_11/bd_6e66_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_12/bd_6e66_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_1/bd_6e66_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_1/bd_6e66_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_5/bd_6e66_s00a2s_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_6/bd_6e66_sarn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_7/bd_6e66_srn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_8/bd_6e66_sawn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_9/bd_6e66_swn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_10/bd_6e66_sbn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_11/bd_6e66_m00s2a_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Redesign_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Redesign_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/researchadmin/ConvBlock/ConvBlock.srcs/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/Redesign_smartconnect_0_1.xci
# IP: The module: 'Redesign_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/bd_6e66.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_0/bd_6e66_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_1/bd_6e66_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_2/bd_6e66_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_3/bd_6e66_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_4/bd_6e66_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_5/bd_6e66_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_6/bd_6e66_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_7/bd_6e66_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_8/bd_6e66_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_9/bd_6e66_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_10/bd_6e66_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_11/bd_6e66_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_12/bd_6e66_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_1/bd_6e66_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_1/bd_6e66_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_5/bd_6e66_s00a2s_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_6/bd_6e66_sarn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_7/bd_6e66_srn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_8/bd_6e66_sawn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_9/bd_6e66_swn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_10/bd_6e66_sbn_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/bd_0/ip/ip_11/bd_6e66_m00s2a_0_ooc.xdc

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Redesign_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/researchadmin/ConvBlock/ConvBlock.gen/sources_1/bd/Redesign/ip/Redesign_smartconnect_0_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Redesign_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
